#!/bin/bash -e

UNIT="timetest"

echo -n "Enabling $UNIT... "
/bin/systemctl enable $UNIT >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

echo -n "Starting $UNIT... "
/bin/systemctl start $UNIT >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

exit 0
